
  CREATE TABLE "BD_DIVISIONS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(100), 
	"BN_NAME" VARCHAR2(100), 
	"URL" VARCHAR2(100), 
	 CONSTRAINT "PK_BD_DIVISION_ID" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;