
  CREATE TABLE "BD_DISTRICTS" 
   (	"ID" NUMBER, 
	"DIVISION_ID" NUMBER, 
	"NAME" VARCHAR2(100), 
	"BN_NAME" VARCHAR2(100), 
	"LAT" VARCHAR2(100), 
	"LON" VARCHAR2(100), 
	"URL" VARCHAR2(100), 
	 CONSTRAINT "PK_BD_DISTRICT_ID" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "BD_DISTRICTS" ADD CONSTRAINT "PK_BD_DISTRICT_DIV_ID" FOREIGN KEY ("DIVISION_ID")
	  REFERENCES "BD_DISTRICTS" ("ID") ENABLE;