
  CREATE TABLE "BD_UPAZILAS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DISTRICT_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(125) NOT NULL ENABLE, 
	"BN_NAME" VARCHAR2(125), 
	"URL" VARCHAR2(150), 
	 CONSTRAINT "PK_UPAZILA_ID" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "BD_UPAZILAS" ADD CONSTRAINT "FK_UPAZILA_DIST_ID" FOREIGN KEY ("DISTRICT_ID")
	  REFERENCES "BD_DISTRICTS" ("ID") ENABLE;