
  CREATE TABLE "BD_UNIONS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"UPAZILLA_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(125) NOT NULL ENABLE, 
	"BN_NAME" VARCHAR2(125) NOT NULL ENABLE, 
	"URL" VARCHAR2(150) NOT NULL ENABLE, 
	 CONSTRAINT "PK_BD_UNION_ID" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "BD_UNIONS" ADD CONSTRAINT "FK_BD_UNION_UPAZILLA_ID" FOREIGN KEY ("UPAZILLA_ID")
	  REFERENCES "BD_UPAZILAS" ("ID") ENABLE;