
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ITEM_STOCK_VW" ("ID", "UNIT", "IN_QTY", "OUT_QTY", "DAMAGE", "BAL") AS 
  SELECT ITEM_ID,UNIT_ID,sum(DECODE(STATUS,'I',QTY,0))IN_QTY,sum(DECODE(STATUS,'O',QTY,0))OUT_QTY,sum(DECODE(STATUS,'D',QTY,0))Damage,sum(DECODE(STATUS,'I',QTY,0)-DECODE(STATUS,'O',QTY,0)-DECODE(STATUS,'D',QTY,0)) BAL
FROM(
SELECT STOCK_TYPE STATUS, ITEM_ID,UNIT_ID,SUM(QTY)QTY FROM STOCK_DTL GROUP BY ITEM_ID,UNIT_ID,STOCK_TYPE
UNION ALL
SELECT 'O' STATUS,ITEM_ID,UOM_ID UNIT_ID,SUM(QTY)QTY FROM DELIVERY_DETAILS
where DELIVERY_ID IN(SELECT DELIVERY_ID FROM DELIVERY_MASTER WHERE STATUS='Y')
 GROUP BY ITEM_ID,UOM_ID
)
group by ITEM_ID,UNIT_ID
ORDER BY ITEM_ID;