
  CREATE TABLE "STOCK_DTL" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"STOCK_ID" NUMBER, 
	"ITEM_ID" NUMBER, 
	"UNIT_ID" NUMBER, 
	"QTY" NUMBER DEFAULT 0, 
	"REMARKS" VARCHAR2(200), 
	"STOCK_TYPE" VARCHAR2(2) DEFAULT 'I', 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;