
  CREATE TABLE "VICTIMS" 
   (	"FULL_NAME" VARCHAR2(150) NOT NULL ENABLE, 
	"FULL_NAME_BN" VARCHAR2(350), 
	"DOB" DATE, 
	"AGE" NUMBER, 
	"GENDER" VARCHAR2(10) NOT NULL ENABLE, 
	"MARITAL_STATUS" VARCHAR2(30), 
	"NID" VARCHAR2(30), 
	"CONTACT_NO" VARCHAR2(20), 
	"FAMILY_MEMBERS" NUMBER, 
	"OCCUPATION" VARCHAR2(150), 
	"INCOME_LEVEL" VARCHAR2(50), 
	"DIVISION_ID" NUMBER, 
	"DISTRICT_ID" NUMBER, 
	"UPAZILA_ID" NUMBER, 
	"UNION_ID" NUMBER, 
	"VILLAGE_NAME" VARCHAR2(150), 
	"LOCATION_DETAILS" VARCHAR2(255), 
	"GEO_LAT" NUMBER, 
	"GEO_LON" NUMBER, 
	"NEEDS_DESCRIPTION" VARCHAR2(255), 
	"PHOTO" BLOB, 
	"FILE_NAME" VARCHAR2(150), 
	"MIME_TYPE" VARCHAR2(150), 
	"DISASTER_ID" NUMBER NOT NULL ENABLE, 
	"REGISTERED_AT" DATE DEFAULT SYSDATE, 
	"RELIEF_RECEIVED" VARCHAR2(1) DEFAULT 'N', 
	"VICTIM_ID" NUMBER, 
	"RELIGION" VARCHAR2(25) DEFAULT 'Islam', 
	 CHECK (gender IN ('Male', 'Female', 'Other')) ENABLE, 
	 CONSTRAINT "PK_VICTIM_VICTIM_ID" PRIMARY KEY ("VICTIM_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UK_VICTIM_NID" UNIQUE ("VICTIM_ID", "NID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UK_VICTIM_PHN" UNIQUE ("VICTIM_ID", "CONTACT_NO")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "VICTIMS" ADD CONSTRAINT "FK_VICTIMS_DISASTER" FOREIGN KEY ("DISASTER_ID")
	  REFERENCES "DISASTERS" ("DISASTER_ID") ENABLE;
  ALTER TABLE "VICTIMS" ADD CONSTRAINT "FK_VICTIMS_DIST_ID" FOREIGN KEY ("DISTRICT_ID")
	  REFERENCES "BD_DISTRICTS" ("ID") ENABLE;
  ALTER TABLE "VICTIMS" ADD CONSTRAINT "FK_VICTIMS_DIV_ID" FOREIGN KEY ("DIVISION_ID")
	  REFERENCES "BD_DIVISIONS" ("ID") ENABLE;
  ALTER TABLE "VICTIMS" ADD CONSTRAINT "FK_VICTIMS_UNION_ID" FOREIGN KEY ("UNION_ID")
	  REFERENCES "BD_UNIONS" ("ID") ENABLE;
  ALTER TABLE "VICTIMS" ADD CONSTRAINT "FK_VICTIMS_UPZLA_ID" FOREIGN KEY ("UPAZILA_ID")
	  REFERENCES "BD_UPAZILAS" ("ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "VICTIMS_TRG" 
   before insert or update ON VICTIMS
   for each row
begin
      if inserting then
         if :NEW.VICTIM_ID is null then
           select NVL(MAX(VICTIM_ID),0)+1  into :new.VICTIM_ID
           from VICTIMS;
         end if;
        
      end if;
      
END;
/
ALTER TRIGGER "VICTIMS_TRG" ENABLE;