
  CREATE TABLE "VICTIM_NEEDS_ITEMS" 
   (	"NEED_ID" NUMBER, 
	"VICTIM_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_ID" NUMBER, 
	"UOM_ID" NUMBER, 
	"QUANTITY" NUMBER, 
	"PRIORITY_LEVEL" VARCHAR2(20), 
	"NEED_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(20) DEFAULT 'Pending', 
	"REMARKS" VARCHAR2(100), 
	 CHECK (PRIORITY_LEVEL IN ('High', 'Medium', 'Low')) ENABLE, 
	 CHECK (STATUS IN ('Pending', 'Fulfilled', 'Cancelled')) ENABLE, 
	 CONSTRAINT "PK_VICTIM_NEEDS_ITEMS_ID" PRIMARY KEY ("NEED_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UK_VICTIM_NEEDS_VICTIM_ID_ITEM_ID" UNIQUE ("VICTIM_ID", "ITEM_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "VICTIM_NEEDS_ITEMS" ADD CONSTRAINT "PK_VICTIM_NEEDS_ITEM_ID" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "RELIEF_ITEMS" ("ITEM_ID") ENABLE;
  ALTER TABLE "VICTIM_NEEDS_ITEMS" ADD CONSTRAINT "PK_VICTIM_NEEDS_VICTIM_ID" FOREIGN KEY ("VICTIM_ID")
	  REFERENCES "VICTIMS" ("VICTIM_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "VICTIM_NEEDS_ITEMS_TRG" 
   before insert or update ON VICTIM_NEEDS_ITEMS
   for each row
begin
      if inserting then
         if :NEW.NEED_ID is null then
           select NVL(MAX(NEED_ID),0)+1  into :new.NEED_ID
           from VICTIM_NEEDS_ITEMS;
         end if;
        
      end if;
      
END;
/
ALTER TRIGGER "VICTIM_NEEDS_ITEMS_TRG" ENABLE;