
  CREATE TABLE "VOLUNTEERS" 
   (	"VOLUNTEER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"FULL_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"GENDER" VARCHAR2(25), 
	"RELIGION" VARCHAR2(25), 
	"DOB" DATE, 
	"AGE" NUMBER, 
	"NID" VARCHAR2(30), 
	"EMAIL" VARCHAR2(100), 
	"PHONE" VARCHAR2(20), 
	"DIVISION_ID" NUMBER, 
	"DISTRICT_ID" NUMBER, 
	"ADDRESS" VARCHAR2(200), 
	"CITY" VARCHAR2(50), 
	"EMERGENCY_CONTACT" VARCHAR2(50), 
	"SKILL_SET" VARCHAR2(200), 
	"AVAILABILITY" VARCHAR2(50), 
	"ROLE" VARCHAR2(50), 
	"ASSIGNED_CAMP" VARCHAR2(100), 
	"JOIN_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(20) DEFAULT 'Active', 
	"IN_ACTIVE_DATE" DATE, 
	"PHOTO" BLOB, 
	"FILE_NAME" VARCHAR2(150), 
	"MIME_TYPE" VARCHAR2(150), 
	"REMARKS" VARCHAR2(200), 
	 CONSTRAINT "PK_VOLUNTEERS_VOLUNTEER_ID" PRIMARY KEY ("VOLUNTEER_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "VOLUNTEERS" ADD CONSTRAINT "FL_VOLUNTEER_DIST_ID" FOREIGN KEY ("DISTRICT_ID")
	  REFERENCES "BD_DISTRICTS" ("ID") ENABLE;
  ALTER TABLE "VOLUNTEERS" ADD CONSTRAINT "FL_VOLUNTEER_DIV_ID" FOREIGN KEY ("DIVISION_ID")
	  REFERENCES "BD_DIVISIONS" ("ID") ENABLE;